# Oliver-OS Complete Monitoring Stack
# Prometheus + Grafana for all databases and services

version: '3.8'

services:
  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: oliver-os-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - oliver-os-network

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: oliver-os-grafana
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - oliver-os-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  oliver-os-network:
    external: true
