# Oliver-OS Complete Database Monitoring
# Prometheus configuration for all 5 databases

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL Database Monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis Cache Monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Neo4j Graph Database Monitoring
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # ChromaDB Vector Database Monitoring
  - job_name: 'chromadb'
    static_configs:
      - targets: ['chromadb:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Elasticsearch Search Engine Monitoring
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 10s

  # Oliver-OS Backend Monitoring (when deployed)
  - job_name: 'oliver-os-backend'
    static_configs:
      - targets: ['oliver-os:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # AI Services Monitoring (when deployed)
  - job_name: 'ai-services'
    static_configs:
      - targets: ['ai-services:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
