name: Status Badge

on:
  workflow_run:
    workflows: ["Smart Assistance CI/CD Pipeline"]
    types: [completed]

jobs:
  update-status:
    name: Update Status Badge
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    steps:
      - name: Update README with status
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read current README
            const readmePath = path.join(process.cwd(), 'README.md');
            let readme = fs.readFileSync(readmePath, 'utf8');
            
            // Update status badge
            const status = '${{ github.event.workflow_run.conclusion }}';
            const badgeUrl = `https://github.com/${{ github.repository }}/actions/workflows/ci.yml/badge.svg`;
            const workflowUrl = `https://github.com/${{ github.repository }}/actions/workflows/ci.yml`;
            
            const statusBadge = `[![CI/CD Status](${badgeUrl})](${workflowUrl})`;
            
            // Update or add status badge
            if (readme.includes('[![CI/CD Status]')) {
              readme = readme.replace(/\[!\[CI\/CD Status\].*?\]\(.*?\)/g, statusBadge);
            } else {
              readme = `# Smart Assistance System\n\n${statusBadge}\n\n${readme}`;
            }
            
            // Write updated README
            fs.writeFileSync(readmePath, readme);
            
            // Commit changes
            const { execSync } = require('child_process');
            execSync('git config --local user.email "action@github.com"');
            execSync('git config --local user.name "GitHub Action"');
            execSync('git add README.md');
            execSync('git commit -m "Update CI/CD status badge" || exit 0');
            execSync('git push');
